apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment-oct01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: azcontainerreg01oct.azurecr.io/my-vk-01oct-custom-app:v1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service-oct01
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: web-app
